services:
  db:
    image: postgres
    container_name: postgres-container
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
        test: pg_isready -U postgres -d postgres
        interval: 3s
        timeout: 10s
        retries: 5
  app:
    container_name: web-app-container
    build: .
    ports:
      - "8080:8080"
    links:
      - "db:database"
    depends_on:
      db:
        condition: service_healthy